In [6]:
import torch
input_ids = torch.tensor([2,3,5,1])

/opt/anaconda3/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [8]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [14]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [26]:
print(embedding_layer(torch.tensor([3])))
print(embedding_layer(torch.tensor([2])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)
tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)


In [28]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


<h1>Positional Embeddings</h1>

In [42]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [46]:
print(token_embedding_layer.weight)

Parameter containing:
tensor([[ 1.3010,  1.2753, -0.2010,  ...,  1.1161,  0.3888,  1.3232],
        [ 0.7034, -0.3659, -0.1965,  ..., -0.7667, -0.6089, -0.0257],
        [-0.2765, -0.0540,  0.6673,  ..., -1.2510,  1.9390,  0.8369],
        ...,
        [ 0.6968, -1.0665,  0.3242,  ..., -0.4655,  1.4674, -1.0565],
        [ 0.8861,  0.0780,  1.0576,  ..., -0.3208, -0.8468, -0.3132],
        [ 0.1119, -0.4229, -0.8296,  ..., -1.0095,  0.9394, -1.5129]],
       requires_grad=True)


In [51]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
max_length = 4
data_loader = create_dataloader_v